// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA9fNWJ2XlQpyqcRipkNlKTC5defIJlKY',
    appId: '1:818160594091:web:6a5b307696f465c31cdbee',
    messagingSenderId: '818160594091',
    projectId: 'read-project-b101f',
    authDomain: 'read-project-b101f.firebaseapp.com',
    storageBucket: 'read-project-b101f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9GhQVEtepc5ji1KuLS2GCL24JQnDscMs',
    appId: '1:818160594091:android:223ebbf8fc2423ae1cdbee',
    messagingSenderId: '818160594091',
    projectId: 'read-project-b101f',
    storageBucket: 'read-project-b101f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCISQubbTJjizYjL6wWxJgePf56_2mRQlQ',
    appId: '1:818160594091:ios:fcfdb2cd593b1b711cdbee',
    messagingSenderId: '818160594091',
    projectId: 'read-project-b101f',
    storageBucket: 'read-project-b101f.appspot.com',
    iosBundleId: 'com.example.readBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCISQubbTJjizYjL6wWxJgePf56_2mRQlQ',
    appId: '1:818160594091:ios:1f6e94f6329feb261cdbee',
    messagingSenderId: '818160594091',
    projectId: 'read-project-b101f',
    storageBucket: 'read-project-b101f.appspot.com',
    iosBundleId: 'com.example.readBuddy.RunnerTests',
  );
}
